# Generated by Django 3.1.7 on 2021-03-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('estado', models.IntegerField()),
            ],
            options={
                'verbose_name': ('Usuario',),
                'verbose_name_plural': ('Usuarios',),
                'db_table': 'usuario',
            },
        ),
    ]
